export const cardArray = [
  {
    id: 1,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 1',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
  {
    id: 2,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 2',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
  {
    id: 3,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 3',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
  {
    id: 4,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 4',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
  {
    id: 5,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 5',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
  {
    id: 6,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 6',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
  {
    id: 7,
    img: '/img/card-image.png',
    title: 'Заголовок в карточке 7',
    price: '170 ₽',
    location: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
  },
];
